### ISSUE TITLE
Tux Version

### ISSUE THREAD

**Issue by amayer5125** [CaptainStitch/linux-wallpapers#2]
I think it would be cool to add a Tux variant. I made a grid of different options but I am not a designer so I have no idea which one would look best. If I had to pick one I would go with the top-right or the bottom-right personally.
![screenshot-2018-07-19-011133](https://user-images.githubusercontent.com/3212673/42923154-0f28d798-8af2-11e8-9094-c4cdbe8d01df.png)

I got the logo from [Wikipedia](https://en.wikipedia.org/wiki/File:NewTux.svg). It is released under the GPL.

If we pick a version I am willing to make a pull request.

**Comment by CaptainStitch** [comment]
Yeah, a distro-independent or general GNU/Linux collection would be cool to add.

They all look good, really. You could keep all 9 in the SVG and just render the ones you'd like to use personally. I'll render variations of it if they are requested. Is render the right word here?

Either way, thank you.

**Comment by amayer5125** [comment]
I kept 6 of the nine above in the svg file. I ended up going with a gray and white version inside a blue circle. I think it looks really nice.

The only thing I am not sure how to do is make the glow around the circle.

**Comment by CaptainStitch** [comment]
Awesome, I merged it.

If you wan to make a glow effect, just copy the circle, blur it a bit, then put it behind the other one. You can play around with the amount of blurring to get the effect you like.

![two circles](https://user-images.githubusercontent.com/41341752/42993384-3b44db0a-8bd9-11e8-9626-365cfb483d49.png)

![glow](https://user-images.githubusercontent.com/41341752/42993398-4378375e-8bd9-11e8-99af-99d8453a81fc.png)
