### ISSUE TITLE
Inkscape Palette

### ISSUE THREAD

**Issue by amayer5125** [CaptainStitch/linux-wallpapers#6]
I made a palette file for Inkscape. It makes changing colors so much simpler. You can find it at https://github.com/amayer5125/arc-theme-palette

To install it I just place it in ~/.config/inkscape/palettes. Then restart inkscape. There is a little **<** next to the colors at the bottom. If you click that you should now see "Arc" listed with all Arc specific colors.

**Comment by CaptainStitch** [comment]
Awesome, I’ll check it out. Thank you again.

**Comment by amayer5125** [comment]
After you test it out let me know. I can send a PR to add it to the README if you would like. That way people working on new wallpapers have an easy way to change colors.
